export const providerAEvents = [
  {
    id: '1',
    title: 'Athena - Berlin Konseri',
    category: 'concert',
    date: '2025-11-15',
    time: '20:00',
    city: 'Bursa',
    venue: 'Volkswagen Arena',
    platform: 'Biletix',
    image: 'https://images.unsplash.com/photo-1648260029310-5f1da359af9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb25jZXJ0JTIwY3Jvd2QlMjBsaWdodHN8ZW58MXx8fHwxNzYxMzI0NTQyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türk pop müziğinin efsane ismi Tarkan, Las Vegas konseri ile İstanbul\'da hayranlarıyla buluşuyor. Unutulmaz bir gece için yerinizi ayırtın!',
    price: '₺520 - ₺1450',
    ticketUrl: 'https://biletix.com',
    
  },
  {
    id: '2',
    title: 'Kenter Tiyatrosu - Macbeth',
    category: 'theater',
    date: '2025-11-08',
    time: '19:30',
    city: 'Konya',
    venue: 'Büyük Tiyatro',
    platform: 'Bubilet',
    image: 'https://images.unsplash.com/photo-1539964604210-db87088e0c2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGVhdGVyJTIwc3RhZ2UlMjBwZXJmb3JtYW5jZXxlbnwxfHx8fDE3NjEyNzU3OTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Shakespeare\'in ölümsüz eseri Hamlet, Devlet Tiyatroları yorumuyla sahneye taşınıyor. Klasik tiyatro severlerin kaçırmaması gereken bir gösteri.',
    price: '₺150 - ₺340',
    ticketUrl: 'https://bubilet.com',
  },
  {
    id: '3',
    title: 'Anadolu Efes vs Real Madrid',
    category: 'sports',
    date: '2025-11-20',
    time: '19:00',
    city: 'Adana',
    venue: 'Türk Telekom Stadyumu',
    platform: 'Passo',
    image: 'https://images.unsplash.com/photo-1631746410377-b0e23f61d083?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcG9ydHMlMjBzdGFkaXVtJTIwY3Jvd2R8ZW58MXx8fHwxNzYxMzExNTY0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türk futbolunun en büyük derbisi! Galatasaray ve Fenerbahçe arasındaki heyecan dolu mücadeleyi kaçırmayın.',
    price: '₺950 - ₺3800',
    ticketUrl: 'https://passo.com',
    
  },
  {
    id: '4',
    title: 'Electronica Sunset Antalya',
    category: 'festival',
    date: '2025-12-01',
    time: '14:00',
    city: 'Bodrum',
    venue: 'Çeşme Plajı',
    platform: 'Mobilet',
    image: 'https://images.unsplash.com/photo-1652093249239-25f1ddb549de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNpYyUyMGZlc3RpdmFsJTIwb3V0ZG9vcnxlbnwxfHx8fDE3NjEyNjI5NjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: '3 gün 3 gece elektronik müzik, deniz, kumsal ve eğlence! Dünyaca ünlü DJ\'ler ve unutulmaz performanslar.',
    price: '₺720 - ₺1950',
    ticketUrl: 'https://mobilet.com',
  },
  {
    id: '5',
    title: 'Manga - Akustik Gece',
    category: 'concert',
    date: '2025-11-12',
    time: '21:00',
    city: 'Eskişehir',
    venue: 'MEB Şura Salonu',
    platform: 'Biletix',
    image: 'https://images.unsplash.com/photo-1616688920494-6758cf681803?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb2NrJTIwYmFuZCUyMGNvbmNlcnR8ZW58MXx8fHwxNzYxMzMwNjY2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türk rock müziğinin köklü grubu Duman, özel akustik düzenleme ile sevilen şarkılarını seslendiriyor.',
    price: '₺390 - ₺900',
    ticketUrl: 'https://biletix.com',
  },
  {
    id: '6',
    title: 'İDOB - Carmen Operası',
    category: 'theater',
    date: '2025-11-10',
    time: '20:00',
    city: 'Gaziantep',
    venue: 'Zorlu PSM',
    platform: 'Bubilet',
    image: 'https://images.unsplash.com/photo-1519683384663-c9b34271669a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvcmNoZXN0cmElMjBjbGFzc2ljYWwlMjBtdXNpY3xlbnwxfHx8fDE3NjEzMzE1Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Klasik müziğin en seçkin eserleri, İstanbul Devlet Opera ve Balesi orkestrası eşliğinde seslendirilecek.',
    price: '₺230 - ₺680',
    ticketUrl: 'https://bubilet.com',
  },
  {
    id: '7',
    title: 'Karadeniz Derbisi - Giresun vs Rize',
    category: 'sports',
    date: '2025-11-18',
    time: '19:00',
    city: 'Trabzon',
    venue: 'Vodafone Park',
    platform: 'Passo',
    image: 'https://images.unsplash.com/photo-1698844013403-b7c4cf0d3b2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHN0YWRpdW0lMjBtYXRjaHxlbnwxfHx8fDE3NjEzMzE1Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Süper Lig\'in heyecan dolu mücadelesi. Beşiktaş evinde Trabzonspor ile karşı karşıya geliyor.',
    price: '₺640 - ₺2950',
    ticketUrl: 'https://passo.com',
  },
  {
    id: '8',
    title: 'Fazıl Say - 30. Yıl Konseri',
    category: 'concert',
    date: '2025-12-05',
    time: '20:30',
    city: 'Mersin',
    venue: 'Kültürpark Açık Hava',
    platform: 'Biletix',
    image: 'https://images.unsplash.com/photo-1548163111-bc419d75fef4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXp6JTIwbXVzaWMlMjBjbHVifGVufDF8fHx8MTc2MTMzMTUyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türk pop müziğinin mimarı Sezen Aksu, 50. sanat yılında İzmir\'de unutulmaz bir konser veriyor.',
    price: '₺520 - ₺1600',
    ticketUrl: 'https://biletix.com',
    
  },
  {
    id: '9',
    title: 'Capital Jazz Nights',
    category: 'festival',
    date: '2025-11-25',
    time: '18:00',
    city: 'Samsun',
    venue: 'Congresium',
    platform: 'Mobilet',
    image: 'https://images.unsplash.com/photo-1548163111-bc419d75fef4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXp6JTIwbXVzaWMlMjBjbHVifGVufDF8fHx8MTc2MTMzMTUyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Yerel ve uluslararası jazz sanatçılarının buluştuğu 3 günlük özel festival. Caz müziği severler için kaçırılmayacak bir etkinlik.',
    price: '₺320 - ₺980',
    ticketUrl: 'https://mobilet.com',
  },
  {
    id: '10',
    title: 'Müjdat Gezen - Cumhuriyet Müzikali',
    category: 'theater',
    date: '2025-11-22',
    time: '20:00',
    city: 'Kayseri',
    venue: 'Zorlu PSM',
    platform: 'Bubilet',
    image: 'https://images.unsplash.com/photo-1539964604210-db87088e0c2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGVhdGVyJTIwc3RhZ2UlMjBwZXJmb3JtYW5jZXxlbnwxfHx8fDE3NjEyNzU3OTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Arabeskın Kralı Müslüm Gürses\'in hayat hikayesi müzikal olarak sahnede. Duygusal ve etkileyici bir performans.',
    price: '₺300 - ₺820',
    ticketUrl: 'https://bubilet.com',
  },
  {
    id: '11',
    title: 'Rock Rüzgarı 2025',
    category: 'festival',
    date: '2025-12-15',
    time: '12:00',
    city: 'Çanakkale',
    venue: 'İstanbul Park',
    platform: 'Mobilet',
    image: 'https://images.unsplash.com/photo-1652093249239-25f1ddb549de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNpYyUyMGZlc3RpdmFsJTIwb3V0ZG9vcnxlbnwxfHx8fDE3NjEyNjI5NjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türkiye\'nin en büyük rock festivali! Uluslararası ve yerli sanatçılarla 2 gün boyunca rock müzik ziyafeti.',
    price: '₺880 - ₺2400',
    ticketUrl: 'https://mobilet.com',
    
  },
  {
    id: '12',
    title: 'EuroLeague Cup - Monaco vs Fenerbahçe',
    category: 'sports',
    date: '2025-11-28',
    time: '20:00',
    city: 'Kocaeli',
    venue: 'Antalya Spor Salonu',
    platform: 'Passo',
    image: 'https://images.unsplash.com/photo-1631746410377-b0e23f61d083?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcG9ydHMlMjBzdGFkaXVtJTIwY3Jvd2R8ZW58MXx8fHwxNzYxMzExNTY0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Basketbol Süper Ligi\'nde heyecan dolu karşılaşma. Antalya Basketbol evinde Fenerbahçe\'yi konuk ediyor.',
    price: '₺220 - ₺820',
    ticketUrl: 'https://passo.com',
  },
  {
    id: '13',
    title: 'Mor ve Ötesi - Kış Turnesi',
    category: 'concert',
    date: '2025-11-14',
    time: '21:00',
    city: 'İzmir',
    venue: 'Küçükçiftlik Park',
    platform: 'Biletix',
    image: 'https://images.unsplash.com/photo-1616688920494-6758cf681803?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb2NrJTIwYmFuZCUyMGNvbmNlcnR8ZW58MXx8fHwxNzYxMzMwNjY2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türk alternatif rock sahnesinin öncü grubu Mor ve Ötesi, İstanbul\'da sahne alıyor.',
    price: '₺430 - ₺990',
    ticketUrl: 'https://biletix.com',
  },
  {
    id: '14',
    title: 'Stand-Up Gala - Kaan Sekban',
    category: 'theater',
    date: '2025-11-16',
    time: '21:00',
    city: 'Diyarbakır',
    venue: 'Congresium',
    platform: 'Bubilet',
    image: 'https://images.unsplash.com/photo-1539964604210-db87088e0c2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGVhdGVyJTIwc3RhZ2UlMjBwZXJmb3JtYW5jZXxlbnwxfHx8fDE3NjEyNzU3OTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türkiye\'nin en sevilen komedyeni Cem Yılmaz, yeni stand-up gösterisiyle Ankara\'da.',
    price: '₺360 - ₺840',
    ticketUrl: 'https://bubilet.com',
    
  },
  {
    id: '15',
    title: 'Göksel - Lo-Fi Sessions',
    category: 'concert',
    date: '2025-11-19',
    time: '20:30',
    city: 'Malatya',
    venue: 'Bostanlı Açık Hava',
    platform: 'Mobilet',
    image: 'https://images.unsplash.com/photo-1548163111-bc419d75fef4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXp6JTIwbXVzaWMlMjBjbHVifGVufDF8fHx8MTc2MTMzMTUyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Pop müziğin sevilen sesi Göksel, İzmir\'de özel akustik performans sergileyecek.',
    price: '₺320 - ₺740',
    ticketUrl: 'https://mobilet.com',
  },
  {
    id: '16',
    title: 'Altın Portakal Film Günleri',
    category: 'festival',
    date: '2025-12-10',
    time: '18:00',
    city: 'Van',
    venue: 'Cam Piramit',
    platform: 'Mobilet',
    image: 'https://images.unsplash.com/photo-1652093249239-25f1ddb549de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNpYyUyMGZlc3RpdmFsJTIwb3V0ZG9vcnxlbnwxfHx8fDE3NjEyNjI5NjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: '5 gün sürecek film gösterimleri, atölyeler ve ünlü sinemacılarla söyleşiler.',
    price: '₺180 - ₺540',
    ticketUrl: 'https://mobilet.com',
    
  },
  {
    id: '17',
    title: 'Kenan Doğulu - Geceyarısı Partisi',
    category: 'concert',
    date: '2025-11-21',
    time: '21:00',
    city: 'İstanbul',
    venue: 'MEB Şura Salonu',
    platform: 'Biletix',
    image: 'https://images.unsplash.com/photo-1648260029310-5f1da359af9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb25jZXJ0JTIwY3Jvd2QlMjBsaWdodHN8ZW58MXx8fHwxNzYxMzI0NTQyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Pop müziğin kralı Kenan Doğulu, en sevilen şarkılarıyla Ankara\'da sahne alıyor.',
    price: '₺470 - ₺1120',
    ticketUrl: 'https://biletix.com',
    
  },
  {
    id: '18',
    title: 'Şahsiyet - Prömiyer Gösterimi',
    category: 'theater',
    date: '2025-11-13',
    time: '20:00',
    city: 'Çorum',
    venue: 'Karşıyaka Sanat Merkezi',
    platform: 'Bubilet',
    image: 'https://images.unsplash.com/photo-1539964604210-db87088e0c2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGVhdGVyJTIwc3RhZ2UlMjBwZXJmb3JtYW5jZXxlbnwxfHx8fDE3NjEyNzU3OTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Psikolojik gerilim türünde çarpıcı bir tiyatro oyunu. İzmir Sanat Tiyatrosu yapımı.',
    price: '₺190 - ₺460',
    ticketUrl: 'https://bubilet.com',
  },
  {
    id: '19',
    title: 'Akdeniz Kupası - Antalyaspor vs Gençlerbirliği',
    category: 'sports',
    date: '2025-11-24',
    time: '19:00',
    city: 'Balıkesir',
    venue: 'Antalya Stadyumu',
    platform: 'Passo',
    image: 'https://images.unsplash.com/photo-1698844013403-b7c4cf0d3b2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb290YmFsbCUyMHN0YWRpdW0lMjBtYXRjaHxlbnwxfHx8fDE3NjEzMzE1Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Süper Lig heyecanı Antalya\'da! Antalyaspor evinde Beşiktaş ile karşılaşıyor.',
    price: '₺360 - ₺1180',
    ticketUrl: 'https://passo.com',
  },
  {
    id: '20',
    title: 'Bülent Ortaçgil - Sahil Özel',
    category: 'concert',
    date: '2025-11-27',
    time: '20:30',
    city: 'Muğla',
    venue: 'Bostanlı Açık Hava',
    platform: 'Biletix',
    image: 'https://images.unsplash.com/photo-1548163111-bc419d75fef4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXp6JTIwbXVzaWMlMjBjbHVifGVufDF8fHx8MTc2MTMzMTUyOHww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Türk müziğinin ustası Bülent Ortaçgil, İzmir\'de unutulmaz bir konser veriyor.',
    price: '₺400 - ₺920',
    ticketUrl: 'https://biletix.com',
  },
];
